## Getting and Knowing your data

In [ ]:
# in pandas we dont consider them array anywore we call them dataframe, we can have of multiple type

### Step 1: Importing the necessary libraries

**Pandas**
* Pandas is an important python lib for data manipulation, wrangling and analysis
* It functions as an intuitive and easy to use set of tools for performing operations of any kind of data
* Iniitial work for pandas was done by Wes McKinney in 2008 while he was a developer at AQR Capital Management. Since then, the scope
of the pandas project has increased a lot 
* Pandas allows you to work with both cross-sectional data and time series base data
* The data representation is done using two primary data type
    - Series
    - Dataframe

In [1]:
import pandas as pd

### Step 2: Import the dataset

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user")

df.head

In [4]:
df.head()

  user_id|age|gender|occupation|zip_code
0                1|24|M|technician|85711
1                     2|53|F|other|94043
2                    3|23|M|writer|32067
3                4|24|M|technician|43537
4                     5|33|F|other|15213

### Step 3: Assign it to a variable called users and use the "user_id" as index

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep='|', index_col = 'user_id')
df.head()

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

In [6]:
# df.reset_index() then we can go back to default index

In [7]:
# if comma was the separator their is no need to mention it

### Step 4: See the first 25 entries

In [8]:
df.head(25)

         age gender     occupation zip_code
user_id
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

In [9]:
# Step 5: See the last 10 entries

In [10]:
df.tail(10)

         age gender     occupation zip_code
user_id
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

In [17]:
# Step 6: What is the number of observations in the dataset?
# is their a way to randomly see the intervals
df.sample(5)

         age gender  occupation zip_code
user_id
782       21      F      artist    33205
415       39      M    educator    85711
690       35      M    salesman    63304
183       33      M   scientist    27708
4         24      M  technician    43537

In [13]:
# what is observation
df.shape

(943, 4)

In [14]:
df.shape[0]

943

In [15]:
# column
df.shape[1]

4

In [16]:
#  Step 7: What is the number of column in dataset

In [18]:
# Step 8: Print the name of all the columns

df.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='str')

In [19]:
# Step 9: How is the dataset indexed?
df.index

RangeIndex(start=1, stop=944, step=1, name='user_id')

In [20]:
#  Step 10: What is the data type of each column

In [21]:
df.dtypes

age           int64
gender          str
occupation      str
zip_code        str
dtype: object

In [22]:
# Step 11: Print only the occupation column
# json or array will be string in dataFrame
# astype to convert the data type

In [24]:
df.iloc[:,2]
# integer location

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: str

In [25]:
df['occupation']

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: str

In [26]:
df.occupation

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: str

In [32]:
df['occupation'].unique()

<StringArray>
[   'technician',         'other',        'writer',     'executive',
 'administrator',       'student',        'lawyer',      'educator',
     'scientist', 'entertainment',    'programmer',     'librarian',
     'homemaker',        'artist',      'engineer',     'marketing',
          'none',    'healthcare',       'retired',      'salesman',
        'doctor']
Length: 21, dtype: str

In [ ]:
# Step 12: How many different occupation in this dataset

In [33]:
df['occupation'].unique().shape

(21,)

In [36]:
df.isna().count()
# non NA cells
# isNull detect missing values

age           943
gender        943
occupation    943
zip_code      943
dtype: int64

In [37]:
df['occupation'].isna()

user_id
1      False
2      False
3      False
4      False
5      False
       ...
939    False
940    False
941    False
942    False
943    False
Name: occupation, Length: 943, dtype: bool

In [38]:
df['occupation'].isna().any()

np.False_

In [34]:
# Step 13: What is the most frequent occupation?

In [41]:
# .dropna() and isna() ---> deals with null value
df['occupation'].value_counts()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

In [42]:
df['occupation'].value_counts().head(1)

occupation
student    196
Name: count, dtype: int64

In [46]:
df['occupation'].value_counts().head(1).index[0]

'student'

In [47]:
# Step 14: Summarize the DataFrame

In [51]:
df.describe()
# works only for numerical column

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

In [52]:
# Step 15 Summalize all the columns

In [53]:
df.describe(include="all")

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

In [54]:
# Step 16: Summarize only the occupation columns

In [55]:
df.occupation.describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

In [56]:
# Step 17: What is the mean age of the users?

In [57]:
df.age.mean()

np.float64(34.05196182396607)

In [58]:
# Step 18: What is the age with least occupation?

In [59]:
df.age.value_counts()

age
30    39
25    38
22    37
28    36
27    35
      ..
7      1
66     1
11     1
10     1
73     1
Name: count, Length: 61, dtype: int64

In [60]:
df.age.value_counts().head(1)

age
30    39
Name: count, dtype: int64

In [61]:
df.age.value_counts().tail(1)

age
73    1
Name: count, dtype: int64