In [2]:
import pandas as pd
import numpy as np

Pandas Series

In [3]:
# Pandas Series is just column and rows
my_series = [5,9,12,27]
my_var = pd.Series(my_series)
my_var
# column

0     5
1     9
2    12
3    27
dtype: int64

In [4]:
# what if we want to pull out from here and do something
my_var[2]

np.int64(12)

In [5]:
# how do we create our own heading 

# need four of them since we have four element in my_series
my_index = ["A","B","C","D"]
my_var2 = pd.Series(my_series, index = my_index)

In [6]:
my_var2
# now we have our own index

A     5
B     9
C    12
D    27
dtype: int64

In [7]:
my_var2["B"]

np.int64(9)

In [8]:
# my_var2[2] doesn't work anymore 
# python dict
cars = {"tesla":12,"Mercedes":42,"BMW":3}
my_var3 = pd.Series(cars)

In [9]:
my_var3
# now we dont need to create a index

tesla       12
Mercedes    42
BMW          3
dtype: int64

Pandas DataFrames

In [10]:
# in DataFrames we can have multiple columns 
from numpy.random import randn

In [11]:
my_data = randn(4,3) #Rows, column
# headers
my_rows = ["A","B","C","D"]
my_cols = ["Monday", "Tuesday","Wednesday"]

In [12]:
# Create dataframe
my_df = pd.DataFrame(my_data, my_rows, my_cols)

In [13]:
my_df

     Monday   Tuesday  Wednesday
A -0.124573  0.608129  -0.519831
B -0.030274 -1.404057  -1.695437
C  1.570614  1.375091   0.312604
D -0.187366 -0.627580   0.865810

In [14]:
# import csv files
# automatically convert to dataFrame
my_df2 = pd.read_csv('dog_data.csv')
my_df2

                    Breed              Color        DogName  OwnerZip
0                COCKAPOO              BROWN        CHARLEY     15236
1            GER SHEPHERD        BLACK/BROWN         TACODA     15238
2           BELG MALINOIS            BRINDLE           EICH     15238
3                   MIXED        BLACK/BROWN          ARROW     15104
4     AM PIT BULL TERRIER        WHITE/BROWN         OAKLEY     15139
...                   ...                ...            ...       ...
2665         GOLDENDOODLE              BROWN        WINSLOW     15044
2666    YORKSHIRE TERRIER        BLACK/BROWN  ROCKY KALAKOS     15220
2667              LAB MIX  WHITE/BLACK/BROWN          ELLIE     15220
2668         GOLDENDOODLE              WHITE       CLARENCE     15143
2669    SHETLAND SHEEPDOG              BLACK        GRIFFIN     15136

[2670 rows x 4 columns]

In [15]:
my_df2.head()

                 Breed        Color  DogName  OwnerZip
0             COCKAPOO        BROWN  CHARLEY     15236
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238
2        BELG MALINOIS      BRINDLE     EICH     15238
3                MIXED  BLACK/BROWN    ARROW     15104
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139

In [16]:
# pull out rows
my_df2.loc[0]

Breed       COCKAPOO
Color          BROWN
DogName      CHARLEY
OwnerZip       15236
Name: 0, dtype: object

In [17]:
# pull out multiple rows
my_df2.loc[[0,5]]

              Breed  Color  DogName  OwnerZip
0          COCKAPOO  BROWN  CHARLEY     15236
5  SCOTTISH TERRIER  BLACK   BAILEY     15129

In [18]:
# Grab first 5 rows
my_df2.head()

                 Breed        Color  DogName  OwnerZip
0             COCKAPOO        BROWN  CHARLEY     15236
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238
2        BELG MALINOIS      BRINDLE     EICH     15238
3                MIXED  BLACK/BROWN    ARROW     15104
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139

In [19]:
# Grab certain no. of first rows
my_df2.head(10)

                 Breed        Color            DogName  OwnerZip
0             COCKAPOO        BROWN            CHARLEY     15236
1         GER SHEPHERD  BLACK/BROWN             TACODA     15238
2        BELG MALINOIS      BRINDLE               EICH     15238
3                MIXED  BLACK/BROWN              ARROW     15104
4  AM PIT BULL TERRIER  WHITE/BROWN             OAKLEY     15139
5     SCOTTISH TERRIER        BLACK             BAILEY     15129
6    YORKSHIRE TERRIER    BLACK/TAN  MIMI PEARL FOSTER     15090
7        DACHSHUND MIX  WHITE/BROWN              LEROI     15101
8    SHETLAND SHEEPDOG  WHITE/BROWN         ZOE VITSAS     15238
9   LABRADOR RETRIEVER       YELLOW              TAFFY     15228

In [20]:
# Grab last 5 row

In [21]:
my_df2.tail()

                  Breed              Color        DogName  OwnerZip
2665       GOLDENDOODLE              BROWN        WINSLOW     15044
2666  YORKSHIRE TERRIER        BLACK/BROWN  ROCKY KALAKOS     15220
2667            LAB MIX  WHITE/BLACK/BROWN          ELLIE     15220
2668       GOLDENDOODLE              WHITE       CLARENCE     15143
2669  SHETLAND SHEEPDOG              BLACK        GRIFFIN     15136

In [22]:
# Get info about the dataframe
my_df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 2670 entries, 0 to 2669
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Breed     2670 non-null   str
 1   Color     2665 non-null   str
 2   DogName   2669 non-null   str
 3   OwnerZip  2670 non-null   int64
dtypes: int64(1), str(3)
memory usage: 148.5 KB

In [23]:
# shape
my_df2.shape

(2670, 4)

In [24]:
my_df2.ndim

2

In [25]:
# get column datatype
my_df2.dtypes

Breed         str
Color         str
DogName       str
OwnerZip    int64
dtype: object

In [26]:
# get some statistics about data
my_df2.describe()

           OwnerZip
count   2670.000000
mean   15268.109738
std     2747.560641
min    15003.000000
25%    15102.000000
50%    15136.000000
75%    15227.000000
max    97206.000000

In [27]:
# Describe specific column 
my_df2['Breed'].describe()

count      2670
unique      185
top       MIXED
freq        235
Name: Breed, dtype: object

In [28]:
my_df2['Color'].describe()

count      2665
unique       72
top       BLACK
freq        371
Name: Color, dtype: object

In [29]:
my_df2['DogName'].describe()

count     2669
unique    1428
top       LUCY
freq        35
Name: DogName, dtype: object

In [30]:
# select specific column using brackets
my_df2['DogName']
# returning Panda Series

0             CHARLEY
1              TACODA
2                EICH
3               ARROW
4              OAKLEY
            ...
2665          WINSLOW
2666    ROCKY KALAKOS
2667            ELLIE
2668         CLARENCE
2669          GRIFFIN
Name: DogName, Length: 2670, dtype: str

In [31]:
# using dot notation
my_df2.DogName

0             CHARLEY
1              TACODA
2                EICH
3               ARROW
4              OAKLEY
            ...
2665          WINSLOW
2666    ROCKY KALAKOS
2667            ELLIE
2668         CLARENCE
2669          GRIFFIN
Name: DogName, Length: 2670, dtype: str

In [32]:
my_df2.iloc[:,2:]

            DogName  OwnerZip
0           CHARLEY     15236
1            TACODA     15238
2              EICH     15238
3             ARROW     15104
4            OAKLEY     15139
...             ...       ...
2665        WINSLOW     15044
2666  ROCKY KALAKOS     15220
2667          ELLIE     15220
2668       CLARENCE     15143
2669        GRIFFIN     15136

[2670 rows x 2 columns]

In [33]:
my_df = pd.read_csv('dog_data.csv')

In [34]:
my_df

                    Breed              Color        DogName  OwnerZip
0                COCKAPOO              BROWN        CHARLEY     15236
1            GER SHEPHERD        BLACK/BROWN         TACODA     15238
2           BELG MALINOIS            BRINDLE           EICH     15238
3                   MIXED        BLACK/BROWN          ARROW     15104
4     AM PIT BULL TERRIER        WHITE/BROWN         OAKLEY     15139
...                   ...                ...            ...       ...
2665         GOLDENDOODLE              BROWN        WINSLOW     15044
2666    YORKSHIRE TERRIER        BLACK/BROWN  ROCKY KALAKOS     15220
2667              LAB MIX  WHITE/BLACK/BROWN          ELLIE     15220
2668         GOLDENDOODLE              WHITE       CLARENCE     15143
2669    SHETLAND SHEEPDOG              BLACK        GRIFFIN     15136

[2670 rows x 4 columns]

How to count data in dataframe

In [35]:
# count distinct value- descending order
my_df['Color'].value_counts()

Color
BLACK                   371
BROWN                   309
WHITE                   226
WHITE/BLACK             196
BLACK/BROWN             183
                       ...
BROWN/ORANGE              1
BLACK/ORANGE/BRINDLE      1
BROWN/FAWN                1
BLACK/BROWN/GREY          1
BROWN/LIVER               1
Name: count, Length: 72, dtype: int64

In [36]:
# ascending
my_df['Color'].value_counts(ascending=True)

Color
BROWN/ORANGE              1
BLACK/ORANGE/BRINDLE      1
BROWN/FAWN                1
BLACK/BROWN/GREY          1
BROWN/LIVER               1
                       ...
BLACK/BROWN             183
WHITE/BLACK             196
WHITE                   226
BROWN                   309
BLACK                   371
Name: count, Length: 72, dtype: int64

In [ ]:
# sometime datamissing and have no value
my_df['DogName'].value_counts()
# we can see that NaN value at row no. 16 is not listed here

DogName
LUCY             35
BELLA            30
BAILEY           29
BUDDY            29
DAISY            26
                 ..
NINO              1
WINSLOW           1
ROCKY KALAKOS     1
CLARENCE          1
GRIFFIN           1
Name: count, Length: 1428, dtype: int64

In [ ]:
my_df['DogName'].value_counts(dropna = False)
# now we can see the length increase by one and if we decrease the dataset we can see that NaN is listed

DogName
LUCY             35
BELLA            30
BAILEY           29
BUDDY            29
DAISY            26
                 ..
NINO              1
WINSLOW           1
ROCKY KALAKOS     1
CLARENCE          1
GRIFFIN           1
Name: count, Length: 1429, dtype: int64

In [39]:
# get relative frequency - Percentage
my_df['Color'].value_counts(normalize = True)

Color
BLACK                   0.139212
BROWN                   0.115947
WHITE                   0.084803
WHITE/BLACK             0.073546
BLACK/BROWN             0.068668
                          ...
BROWN/ORANGE            0.000375
BLACK/ORANGE/BRINDLE    0.000375
BROWN/FAWN              0.000375
BLACK/BROWN/GREY        0.000375
BROWN/LIVER             0.000375
Name: proportion, Length: 72, dtype: float64

In [41]:
# get specific Item Count
# how many white dogs
my_df['Color'].value_counts()['WHITE']

np.int64(226)

In [ ]:
# count unique value - Size
my_df.groupby('Color').size()
# alphabetical order

Color
APRICOT              15
BEIGE                 5
BLACK               371
BLACK WITH WHITE     21
BLACK/BRINDLE         5
                   ...
WHITE/ORANGE          5
WHITE/RED            14
WHITE/TAN            50
WHITE/YELLOW          2
YELLOW               51
Length: 72, dtype: int64

In [ ]:
my_df.groupby('Color').count()
# group by count

                  Breed  DogName  OwnerZip
Color
APRICOT              15       15        15
BEIGE                 5        5         5
BLACK               371      371       371
BLACK WITH WHITE     21       21        21
BLACK/BRINDLE         5        5         5
...                 ...      ...       ...
WHITE/ORANGE          5        5         5
WHITE/RED            14       14        14
WHITE/TAN            50       50        50
WHITE/YELLOW          2        2         2
YELLOW               51       51        51

[72 rows x 3 columns]

In [44]:
# get a count of all column across all columns

In [47]:
# my_df.apply(pd.value_counts)
# syntax changed

Add new columns to Dataframe

In [48]:
my_df = pd.read_csv('dog_data_short.csv')
my_df

                 Breed        Color  DogName  OwnerZip
0             COCKAPOO        BROWN  CHARLEY     15236
1         GER SHEPHERD  BLACK/BROWN   TACODA     15238
2        BELG MALINOIS      BRINDLE     EICH     15238
3                MIXED  BLACK/BROWN    ARROW     15104
4  AM PIT BULL TERRIER  WHITE/BROWN   OAKLEY     15139

In [ ]:
# add column from List